devices([
  "iPhone X",
  "iPhone 8 Plus",
  "iPad Pro (12.9-inch)",
])

languages([
  "en-US",
  "de-DE"
])

scheme("TimeuUITests")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
localize_simulator(true)
